---
title: All I Wanna Buy
timezone: Europe/Paris
collections:
  posts:
    title: Articles
    output: true
  shelves:
    title: Etagères
    output: true
    permalink: "/etageres/:title/index.html"
  uploads:
    title: Fichiers
    output: true
  finds:
    title: Trouvailles
    output: true
    permalink: "/mes-trouvailles/:title/index.html"
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    thumbnail:
- scope:
    path: _finds
    type: finds
  values:
    layout: find
    is_in_bag:
    thumbnail:
    shelves: []
- scope:
    path: _shelves
    type: shelves
  values:
    layout: shelf
    thumbnail:
permalink: "/carnet-de-bord/:title"
