---
title: All I Wanna Buy
timezone: Europe/Paris
collections:
  finds:
    title: Finds
    output: true
    permalink: "/mes-trouvailles/:title/index.html"
    layout: find
  posts:
    title: Posts
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
- scope:
    path: _finds
    type: finds
  values:
    layout: find
