---
title: All I Wanna Buy
timezone: Europe/Paris
collections:
  posts:
    title: Articles
    output: true
  uploads:
    title: Fichiers
    output: true
  finds:
    title: Trouvailles
    output: true
    permalink: "/mes-trouvailles/:title/index.html"
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
- scope:
    path: _finds
    type: finds
  values:
    layout: find
    is_in_bag: false
permalink: "/carnet-de-bord/:title"
