---
title: All I Wanna Buy
timezone: Europe/Paris
permalink: /carnet-de-bord/:title
collections:
  finds:
    title: Trouvailles
    output: true
    permalink: "/mes-trouvailles/:title/index.html"
    layout: find
  posts:
    title: Articles
    output: true
    layout: post
  uploads:
    title: Fichiers
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
- scope:
    path: _finds
    type: finds
  values:
    layout: find
